[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
verbosity = 3
show_progress = true
auto_detect_remappings = false
ignored_warnings_from = ["dependencies/"]

remappings = [
    "@forge-std/=dependencies/forge-std-1.9.7/src/",
    "@solmate/=dependencies/solmate-6.8.0/src/",
    "@solady/=dependencies/solady-0.1.23/src/",
]

[fmt]
ignore = []
tab_width = 4
int_types = "long"
line_length = 120
quote_style = "double"
sort_imports = false
wrap_comments = true
hex_underscore = "preserve"
bracket_spacing = true
override_spacing = false
contract_new_lines = false
number_underscore = "thousands"
multiline_func_header = "params_first"
single_line_statement_blocks = "single"

[invariant]
runs = 256
depth = 500
show_metrics = true
fail_on_revert = true
call_override = false
include_storage = true
shrink_run_limit = 5_000
dictionary_weight = 80
include_push_bytes = true


[dependencies]
forge-std = "1.9.7"
solmate = "6.8.0"
solady = "0.1.23"

[soldeer]
recursive_deps = false
remappings_version = false
remappings_generate = false
remappings_regenerate = false
remappings_prefix = "@"
remappings_location = "config"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
